CREATE TABLE [CharityImport].[extract_charity_import]
(	
	[DateOfExtract] [smalldatetime] NULL,
	[OrganisationNumber] [int] NULL,
	[RegisteredCharityNumber] [int] NULL,
	[LinkedCharityNumber] [int] NULL,
	[CharityName] [varchar](500) NULL,
	[CharityType] [varchar](50) NULL,
	[CharityRegistrationStatus] [varchar](50) NULL,
	[DateOfRegistration] [smalldatetime] NULL,
	[DateOfRemoval] [smalldatetime] NULL,
	[CharityReportingStatus] [varchar](150) NULL,
	[LatestAccFinPeriodStartDate] [smalldatetime] NULL,
	[LatestAccFinPeriodEndDate] [smalldatetime] NULL,
	LatestIncome [numeric](12, 0) NULL,
	[LatestExpenditure] [numeric](12, 0) NULL,
	[CharityContactAddress1] [varchar](50) NULL,
	[CharityContactAddress2] [varchar](50) NULL,
	[CharityContactAddress3] [varchar](50) NULL,
	[CharityContactAddress4] [varchar](50) NULL,
	[CharityContactAddress5] [varchar](50) NULL,
	[CharityContactPostcode] [varchar](8) NULL,
	[CharityContactPhone] [varchar](100) NULL,
	[CharityContactEmail] [varchar](100) NULL,
	[CharityContactWeb] [varchar](400) NULL,
	[CharityCompanyRegistrationNumber] [varchar](100) NULL,
	[CharityInsolvent] [bit] NULL,
	[CharityInAdministration] [bit] NULL,
	[CharityPreviouslyExcepted] [bit] NULL,
	[CharityIsCdfOrCif] [varchar](100) NULL,
	[CharityIsCio] [bit] NULL,
	[CioIsDissolved] [bit] NULL,
	[DateCioDissolutionNotice]  [smalldatetime] NULL,
	[CharityActivities] [nvarchar](max) NULL,
	[CharityGiftAid] [bit] NULL,
	[CharityHasLand] [bit] NULL,
)