IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'charity' AND COLUMN_NAME='name' AND COLUMN_DEFAULT IS NULL)
BEGIN
	UPDATE charity
	   SET Name = ''
	 WHERE Name IS NULL;
END

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'charity' AND COLUMN_NAME='nhs' AND COLUMN_DEFAULT IS NULL)
BEGIN
	UPDATE charity
	   SET nhs = ''
	 WHERE nhs IS NULL;
END

